server:
  port: 8004 # 后台管理系统服务端口号

# 服务名
spring:
  application:
    name: service-cms

# mysql 数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password:

# 返回 json 的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# redis配置信息
  redis:
    host: 101.200.120.89  #主机连接服务名
    port: 6379            #缓存端口号
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1

        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

# nacos服务地址 在客户端微服务中添加注册Nacos服务的配置信息
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/atguigu/educms/mapper/xml/*.xml

#mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
